export const data = [
  {
    name: 'Google',
    path: 'https://www.google.com/',
    prefix: 'https://www.google.com/search?q=',
    suffix: '',
    color: "#4285F4",
    id: 90,
    favicon: 'https://www.google.com/favicon.ico',
  },
  {
    name: 'Google Images',
    path: 'https://www.google.com/imghp',
    prefix: 'https://www.google.com/search?q=',
    suffix: '&tbm=isch',
    color: "#F5AF00",
    id: 12,
    favicon: 'https://www.google.com/favicon.ico',
  },
  {
    name: 'YouTube',
    path: 'https://www.youtube.com/',
    prefix: 'https://www.youtube.com/results?search_query=',
    suffix: '',
    color: '#d71e18',
    id: 2,
    favicon: 'https://s.ytimg.com/yts/img/favicon_144-vfliLAfaB.png',
  },
  {
    name: 'Amazon',
    path: 'https://www.amazon.com/',
    prefix: 'https://www.amazon.com/s?k=',
    suffix: '',
    color: "#EF7A1A",
    id: 3,
    favicon: 'https://www.amazon.com/favicon.ico',
  },
  {
    name: 'Spotify',
    path: 'https://open.spotify.com/',
    prefix: 'https://open.spotify.com/search/',
    suffix: '',
    color: "#1DB954",
    id: 4,
    favicon: 'https://www.scdn.co/i/_global/favicon.png',
  },
  {
    name: 'Wikipedia',
    path: 'https://en.wikipedia.org/wiki/Main_Page',
    prefix: 'https://en.wikipedia.org/w/index.php?&search=',
    suffix: '',
    color: '#505050',
    id: 5,
    favicon: 'https://en.wikipedia.org/favicon.ico',
  },
  {
    name: 'Reddit',
    path: 'https://www.reddit.com/',
    prefix: 'https://www.reddit.com/search/?q=',
    suffix: '',
    color: '#FF5700',
    id: 6,
    favicon: 'https://www.redditstatic.com/desktop2x/img/favicon/apple-icon-120x120.png',
  },
  {
    name: 'Facebook',
    path: 'https://www.facebook.com/',
    prefix: 'https://www.facebook.com/search/top/?q=',
    suffix: '',
    color: '#4267B2',
    id: 97,
    favicon: 'https://facebook.com/favicon.ico',
  },
  {
    name: 'Yahoo',
    path: 'https://www.yahoo.com/',
    prefix: 'https://search.yahoo.com/search?p=',
    suffix: '',
    color: '#720e9e',
    id: 98,
    favicon: 'https://s.yimg.com/rz/l/favicon.ico',
  },
  {
    name: 'eBay',
    path: 'https://www.ebay.com/',
    prefix: 'https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313.TR11.TRC1.A0.H0.Xok.TRS0&_nkw=',
    suffix: '',
    color: '#86B817',
    id: 99,
    favicon: 'https://pages.ebay.com/favicon.ico',
  },
  {
    name: 'Pinterest',
    path: 'https://www.pinterest.com/',
    prefix: 'https://www.pinterest.com/search/pins/?q=',
    suffix: '',
    color: '#c8232c',
    id: 100,
    favicon: 'https://s.pinimg.com/webapp/style/images/favicon-fd1ea058.png',
  },
];
