const arr = [
  'Google',
  'YouTube',
  'Amazon',
  'Spotify',
  'Wikipedia',
  'Google Images',
];

export const data = [
  {
    name: 'Google',
    path: 'https://www.google.com/',
    prefix: 'https://www.google.com/search?q=',
    color: '#4285f4',
    id: 100,
    favicon: 'https://www.google.com/favicon.ico?gws_rd=ssl',
  },
  {
    name: 'Google Images',
    path: 'https://www.google.com/imghp',
    prefix: 'https://www.google.com/search?tbm=isch&q=',
    color: '#fdc216',
    id: 101,
    favicon: 'https://www.google.com/favicon.ico',
  },
  {
    name: 'YouTube',
    path: 'https://www.youtube.com/',
    prefix: 'https://www.youtube.com/results?search_query=',
    color: '#ed1b1a',
    id: 102,
    favicon: 'https://s.ytimg.com/yts/img/favicon_144-vfliLAfaB.png',
  },
  {
    name: 'Amazon',
    path: 'https://www.amazon.com/',
    prefix: 'https://www.amazon.com/s?k=',
    color: '#ff720a',
    id: 103,
    favicon: 'https://www.amazon.com/favicon.ico',
  },
  {
    name: 'Spotify',
    path: 'https://open.spotify.com/',
    prefix: 'https://open.spotify.com/search/',
    color: '#18ca58',
    id: 104,
    favicon: 'https://open.spotify.com/favicon.ico',
  },
  {
    name: 'Wikipedia',
    path: 'https://en.wikipedia.org/wiki/Main_Page',
    prefix: 'https://en.wikipedia.org/w/index.php?&search=',
    color: '#5f5f5f',
    id: 105,
    favicon: 'https://en.wikipedia.org/favicon.ico',
  },
  {
    name: 'Reddit',
    path: 'https://www.reddit.com/',
    prefix: 'https://www.reddit.com/search/?q=',
    color: '#ff720a',
    id: 106,
    favicon:
      'https://www.redditstatic.com/desktop2x/img/favicon/apple-icon-120x120.png',
  },
  {
    name: 'Facebook',
    path: 'https://www.facebook.com/',
    prefix: 'https://www.facebook.com/search/top/?q=',
    color: '#1c50b9',
    id: 107,
    favicon: 'https://m.facebook.com/apple-touch-icon.png',
  },
  {
    name: 'Yahoo!',
    path: 'https://www.yahoo.com/',
    prefix: 'https://search.yahoo.com/search?p=',
    color: '#8715dc',
    id: 108,
    favicon: 'https://s.yimg.com/rz/l/favicon.ico',
  },
  {
    name: 'eBay',
    path: 'https://www.ebay.com/',
    prefix: 'https://www.ebay.com/sch/i.html?_nkw=',
    color: '#00ad8d',
    id: 109,
    favicon: 'https://pages.ebay.com/apple-touch-icon.png',
  },
  {
    name: 'Pinterest',
    path: 'https://www.pinterest.com/',
    prefix: 'https://www.pinterest.com/search/pins/?q=',
    color: '#af0954',
    id: 110,
    favicon: 'https://s.pinimg.com/webapp/style/images/favicon-fd1ea058.png',
  },
  {
    name: 'Netflix',
    path: 'https://www.netflix.com/',
    prefix: 'https://www.netflix.com/search?q=',
    color: '#ed1b1a',
    id: 111,
    favicon: 'https://www.netflix.com/favicon.ico',
  },
  {
    name: 'Bing',
    path: 'https://www.bing.com/',
    prefix: 'https://www.bing.com/search?q=',
    color: '#00ad8d',
    id: 112,
    favicon: 'https://www.bing.com/apple-touch-icon.png',
  },
  {
    name: 'Yelp',
    path: 'https://www.yelp.com/',
    prefix: 'https://www.yelp.com/search?find_desc=',
    color: '#ed1b1a',
    id: 113,
    favicon: 'https://www.yelp.com/favicon.ico',
  },
  {
    name: 'Tripadvisor',
    path: 'https://www.tripadvisor.com/',
    prefix: 'https://www.tripadvisor.com/Search?q=',
    color: '#18ca58',
    id: 114,
    favicon: 'https://www.tripadvisor.com/favicon.ico',
  },
  {
    name: 'IMDb',
    path: 'https://www.imdb.com/',
    prefix: 'https://www.imdb.com/find?q=',
    color: '#fdc216',
    id: 115,
    favicon: 'https://m.imdb.com/favicon.ico',
  },
  {
    name: 'Rotten Tomatoes',
    path: 'https://www.rottentomatoes.com/',
    prefix: 'https://www.rottentomatoes.com/search?search=',
    color: '#ed1b1a',
    id: 116,
    favicon: 'https://www.rottentomatoes.com/favicon.ico',
  },
  {
    name: 'GitHub',
    path: 'https://github.com/',
    prefix: 'https://github.com/search?q=',
    color: '#5f5f5f',
    id: 117,
    favicon: 'https://github.com/favicon.ico',
  },
  {
    name: 'LinkedIn',
    path: 'https://www.linkedin.com/',
    prefix: 'https://www.linkedin.com/search/results/all/?keywords=',
    color: '#4285f4',
    id: 118,
    favicon:
      'https://static-exp1.licdn.com/scds/common/u/images/logos/favicons/v1/favicon.ico',
  },
  {
    name: 'Stack Overflow',
    path: 'https://stackoverflow.com/',
    prefix: 'https://stackoverflow.com/search?q=',
    color: '#ff720a',
    id: 119,
    favicon: 'https://stackoverflow.com/favicon.ico',
  },
  {
    name: 'Twitter',
    path: 'https://twitter.com/',
    prefix: 'https://twitter.com/search?q=',
    color: '#4285f4',
    id: 120,
    favicon: 'https://abs.twimg.com/favicons/twitter.ico',
  },
  {
    name: 'Fandom',
    path: 'https://www.fandom.com/',
    prefix: 'https://www.fandom.com/?s=',
    color: '#00ad8d',
    id: 121,
    favicon: 'https://www.fandom.com/favicon.ico',
  },
  {
    name: 'ESPN',
    path: 'https://www.espn.com/',
    prefix: 'https://www.espn.com/search/_/q/',
    color: '#ed1b1a',
    id: 122,
    favicon: 'https://www.espn.com/favicon.ico',
  },
  {
    name: 'The New York Times',
    path: 'https://www.nytimes.com/',
    prefix: 'https://www.nytimes.com/search?query=',
    color: '#5f5f5f',
    id: 123,
    favicon: 'https://www.nytimes.com/favicon.ico',
  },
  {
    name: 'CNN',
    path: 'https://www.cnn.com/',
    prefix: 'https://www.cnn.com/search?q=',
    color: '#ed1b1a',
    id: 124,
    favicon:
      'https://cdn.cnn.com/cnn/.e/img/3.0/global/misc/apple-touch-icon.png',
  },
  {
    name: 'Twitch',
    path: 'https://www.twitch.tv/',
    prefix: 'https://www.twitch.tv/search?term=',
    color: '#8715dc',
    id: 125,
    favicon: 'https://m.twitch.tv/favicon.ico?desktop-redirect=true',
  },
  {
    name: 'Dictionary.com',
    path: 'https://www.dictionary.com/',
    prefix: 'https://www.dictionary.com/browse/',
    color: '#4285f4',
    id: 126,
    favicon:
      'https://www.dictionary.com/hp-assets/dcom_favicon-1bff2f1b49c077ed504e55c3649f2a4b.png',
  },
  {
    name: 'Thesaurus.com',
    path: 'https://www.thesaurus.com/',
    prefix: 'https://www.thesaurus.com/browse/',
    color: '#fdc216',
    id: 127,
    favicon:
      'https://www.thesaurus.com/hp-assets/tcom_favicon-54545f5303fccb956af394ac10f1655d.png',
  },
  {
    name: 'Merriam Webster',
    path: 'https://www.merriam-webster.com/',
    prefix: 'https://www.merriam-webster.com/dictionary/',
    color: '#00ad8d',
    id: 128,
    favicon: 'https://www.merriam-webster.com/favicon.ico',
  },
  {
    name: 'Britannica',
    path: 'https://www.britannica.com/',
    prefix: 'https://www.britannica.com/search?query=',
    color: '#1c50b9',
    id: 129,
    favicon: 'https://www.britannica.com/favicon.ico',
  },
  {
    name: 'Vimeo',
    path: 'https://vimeo.com/',
    prefix: 'https://vimeo.com/search?q=',
    color: '#4285f4',
    id: 130,
    favicon: 'https://i.vimeocdn.com/favicon/main-touch_180',
  },
];

export const initDashboard = data.filter((item) => arr.includes(item.name));
